### ISSUE TITLE
DockerHub image is missing

### ISSUE THREAD

**Issue by shouldsee** [daknuett/edirect-docker#1]
This command does not work
```
docker run -it -v /path/to/your/pubmed_master:/data daknuett/edirect bash
```

**Comment by daknuett** [comment]
The repostitory  `daknuett/edirect-docker` was built before _ncbi_ created their own docker image.
Not what there is an official image this repository is deprecated. I recommend using
[`ncbi/edirect`](https://hub.docker.com/r/ncbi/edirect) instead.

I will edit the README accordingly and delete the repository in the coming weeks.
